name: CD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-rf:
    name: Installs robot framework
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Build docker image for distribution
        run: docker build -t robot-browser .

      - name: Run robot tests
        run: |
        docker run --rm robot-browser bash -c "robot -v BROWSER:$1 --outputdir /tests/results /tests"

